# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    
  config.vm.define "client1" do |client1|
    client1.vm.box = "ubuntu/trusty64"
    
    #configure networking
    client1.vm.network "private_network", ip: "192.168.100.100"
    client1.vm.provision "shell", run: "always", inline: "route del default"
    client1.vm.provision "shell", run: "always", inline: "route add default gw 192.168.100.1"
    
    client1.vm.provision "shell", inline: "echo client1 finished!!!"
  end
  
  config.vm.define "router" do |router|
    router.vm.box = "ubuntu/trusty64"
    
    #configure networking
    router.vm.network "private_network", ip: "192.168.100.1"
    router.vm.network "private_network", ip: "192.168.200.1"
    router.vm.provision "shell", run: "always", inline: "route del default"
    router.vm.provision "shell", inline: "sudo sysctl -w net.ipv4.ip_forward=1"
    
    router.vm.provision "shell", inline: "echo router finished!!!"
  end
  
  config.vm.define "client2" do |client2|
    client2.vm.box = "ubuntu/trusty64"
    
    #configure networking
    client2.vm.network "private_network", ip: "192.168.200.100"
    client2.vm.provision "shell", run: "always", inline: "route del default"
    client2.vm.provision "shell", run: "always", inline: "route add default gw 192.168.200.1"
    
    client2.vm.provision "shell", inline: "echo client2 finished!!!"
  end
        
end
